services:
  - type: web
    name: lima-nada
    env: ruby
    plan: free
    buildCommand: bundle install && bundle exec rails assets:precompile
    startCommand: bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0 -p $PORT

