default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  prepared_statements: false

development:
  <<: *default
  database: lima_nada_development
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>

test:
  <<: *default
  database: lima_nada_test
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>

production:
  url: <%= ENV["DATABASE_URL"] %>
  prepared_statements: false

